In [1]:
import pandas as pd
from numpy import *
from sklearn.model_selection import train_test_split
from nltk.corpus import stopwords

from sklearn.preprocessing import LabelEncoder , OneHotEncoder

In [2]:
from sklearn.utils import shuffle
import re
from nltk.stem.porter import PorterStemmer
import nltk
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [3]:
header_list = ['Comment','Sentiment','Nan']
cp = pd.read_csv('Roman_Urdu_Dataset.csv',names=header_list)
cp.head()

Comment Sentiment  Nan
0  Sai kha ya her kisi kay bus ki bat nhi hai lak...  Positive  NaN
1                                          sahi bt h  Positive  NaN
2                                        Kya bt hai,  Positive  NaN
3                                         Wah je wah  Positive  NaN
4                               Are wha kaya bat hai  Positive  NaN

In [4]:
cp = cp.drop('Nan',axis = 1)

In [5]:
cp.isnull().sum()

Comment      1
Sentiment    0
dtype: int64

In [6]:
cp.shape

(20229, 2)

In [7]:
cp.shape[0]

20229

In [8]:
cp['Sentiment'].value_counts()

Neutral     8929
Positive    6013
Negative    5286
Neative        1
Name: Sentiment, dtype: int64

In [9]:
cp['Sentiment'] = cp['Sentiment'].replace('Neative','Negative')

In [10]:
cp['Sentiment'].value_counts()

Neutral     8929
Positive    6013
Negative    5287
Name: Sentiment, dtype: int64

In [11]:
pos = cp[cp['Sentiment'] =='Positive'].shape[0]
neg = cp[cp['Sentiment'] =='Negative'].shape[0]
neu = cp[cp['Sentiment'] =='Neutral'].shape[0]

In [12]:
cp.iloc[:,0].values

array(['Sai kha ya her kisi kay bus ki bat nhi hai lakin main ki hal kal bi Aj aur aj bi sirf Aus say bus',
       'sahi bt h', 'Kya bt hai,', ...,
       'Bahi sayasat kufrrr ha saaaf bttttt ha qanon sirf Allah ka Calhay ga Muslim country me sayasat ka kaaaam isreal ka ha',
       'aanti toh gussa e kr gai hain ',
       'mai b sirf shadi kanry ki waja say imran khan ka sat dey raha hun '],
      dtype=object)

In [13]:

le = LabelEncoder()

In [14]:
cp['Sentiment'] = le.fit_transform(cp['Sentiment'])

In [15]:
cp['Sentiment'].unique()

array([2, 1, 0], dtype=int64)

In [16]:
cp = cp.dropna(subset=['Comment'])

In [17]:
cp.reset_index(drop=True, inplace=True)

In [18]:
cp.shape

(20228, 2)

In [19]:
len(cp['Comment'])

20228

In [20]:
corpus=[]
stop=['ai', 'ayi', 'hy', 'hai', 'main', 'ki', 'tha', 'koi', 'ko', 'sy', 'woh', 'bhi', 'aur', 'wo', 'yeh', 'rha', 'hota', 'ho', 'ga', 'ka', 'le', 'lye', 'kr', 'kar', 'lye', 'liye', 'hotay', 'waisay', 'gya', 'gaya', 'kch', 'ab', 'thy', 'thay', 'houn', 'hain', 'han', 'to', 'is', 'hi', 'jo', 'kya', 'thi', 'se', 'pe', 'phr', 'wala', 'waisay', 'us', 'na', 'ny', 'hun', 'rha', 'raha', 'ja', 'rahay', 'abi', 'uski', 'ne', 'haan', 'acha', 'nai', 'sent', 'photo', 'you', 'kafi', 'gai', 'rhy', 'kuch', 'jata', 'aye', 'ya', 'dono', 'hoa', 'aese', 'de', 'wohi', 'jati', 'jb', 'krta', 'lg', 'rahi', 'hui', 'karna', 'krna', 'gi', 'hova', 'yehi', 'jana', 'jye', 'chal', 'mil', 'tu', 'hum', 'par', 'hay', 'kis', 'sb', 'gy', 'dain', 'krny', 'tou']

In [21]:
corpus=[]
for i in range(cp.shape[0]):
    review = re.sub('[^a-zA-Z]'," ",cp.iloc[:,0].values[i])
    review=review.lower()
    review=review.split()
    review=[word for word in review if not word in stop]
    review=' '.join(review)
    corpus.append(review)

In [22]:
len(corpus)

20228

In [23]:
cv = CountVectorizer(max_features=2500)
x = cv.fit_transform(corpus).toarray()

In [24]:
y = cp['Sentiment']

In [25]:
y.unique()

array([2, 1, 0], dtype=int64)

In [26]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [27]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size = 0.2)

In [28]:
pd.DataFrame(xtest)

0     1     2     3     4     5     6     7     8     9     ...  2490  \
0        0     0     0     0     0     0     0     0     0     0  ...     0   
1        0     0     0     0     0     0     0     0     0     0  ...     0   
2        0     0     0     0     0     0     0     0     0     0  ...     0   
3        0     0     0     0     0     0     0     0     0     0  ...     0   
4        0     0     0     0     0     0     0     0     0     0  ...     0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
4041     0     0     0     0     0     0     0     0     0     0  ...     0   
4042     0     0     0     0     0     0     0     0     0     0  ...     0   
4043     0     0     0     0     0     0     0     0     0     0  ...     0   
4044     1     0     0     0     0     0     0     0     0     0  ...     0   
4045     0     0     0     0     0     0     0     0     0     0  ...     0   

      2491  2492  2493  2494  2495  2496  2497  2498  2499  
0        0     0     0     0     0     0     0     0     0  
1        0     0     0     0     0     0     0     0     0  
2        0     0     0     0     0     0     0     0     0  
3        0     0     0     0     0     0     0     0     0  
4        0     0     0     0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
4041     0     0     0     0     0     0     0     0     0  
4042     0     0     0     0     0     0     0     0     0  
4043     0     0     0     0     0     0     0     0     0  
4044     0     0     0     0     0     0     0     0     0  
4045     0     0     0     0     0     0     0     0     0  

[4046 rows x 2500 columns]

In [29]:
# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(xtrain, ytrain)

# Predicting the Test set results
y_pred = classifier.predict(xtest)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(ytest, y_pred)
cm

array([[ 647,  311,   89],
       [ 468, 1186,  175],
       [ 370,  351,  449]], dtype=int64)

In [30]:
from sklearn.metrics import accuracy_score

In [31]:
accuracy_score(ytest, y_pred)

0.5640138408304498

In [32]:
classifier1=LogisticRegression(random_state=0,solver='liblinear',multi_class='auto')
classifier1.fit(xtrain,ytrain)
ypred=classifier1.predict(xtest)


In [33]:
cm1=confusion_matrix(ytest,ypred)
cm1

array([[ 466,  442,  139],
       [ 159, 1479,  191],
       [ 135,  390,  645]], dtype=int64)

In [34]:
accuracy_score(ytest, y_pred)

0.5640138408304498

In [35]:
from sklearn.svm import SVC
model = SVC(kernel='linear', C=1, gamma=1)
model.fit(xtrain,ytrain)
pr = model.predict(xtest)
c = confusion_matrix(ytest,pr)
print(c)
accuracy_score(ytest,pr)

[[ 504  409  134]
 [ 207 1427  195]
 [ 172  350  648]]


0.6374196737518537